### ISSUE TITLE
Code Review 29 September

### ISSUE THREAD

**Issue by yogajones** [PlatinumFoxTail/tikawoh_BCI#1]
I created a separately named database ("tikawoh_bci") to be sure there are no conflicts.
However, installation raises the following error:

```
~/tikawoh_BCI$ psql -d tikawoh_bci < schema.sql
CREATE TABLE
CREATE TABLE
ERROR:  syntax error at or near "ARRAY"
LINE 1: ...acter varying, author character varying, keywords ARRAY, rat...
                                                                                                           ^
CREATE TABLE
```
Please check this. Otherwise the code formatting and structure looks appropriate, although I would consider dividing the code into separate modules.

**Comment by PlatinumFoxTail** [comment]
Thanks for the feedback! I restructered the literature table, so ARRAYS are not part of keywords column anymore. Cloned the repository to another folder on my computer and copied the tables manually to postgresql, and now seems to work.

May I ask at the same time, hwo do get psql -d tikawoh_bci < schema.sql command to work? I only get error messages such as "error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory". Can not put the finger on where the issue is.

**Comment by PlatinumFoxTail** [comment]
Sorted out
